name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: sudo chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      - name: Clear Config and Cache
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Compile assets
        run: |
          npm install
          npm run build

      - name: Run Tests (Unit and Feature tests)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --coverage-clover clover.xml

      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with: 
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
            
